Removing an instance of incorrect span.end() that causes a refCount error in tracing.
Removing an instance of incorrect span.end() that causes a refCount error in tracing.

This pollutes the application logs with unnecessary stacktrace like:
java.lang.IllegalStateException: refCount dropped below zero